# Generated by Django 2.2.1 on 2019-05-05 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1984), django.core.validators.MaxValueValidator(2019)]),
        ),
    ]
